pipeline{
    agent{
        docker{
            image 'selenium/standalone-firefox:3.141.59-gold'
            args '-p 3030:3030'
        }
    }

    stages{
        stage('Build'){
            steps{
                sh 'npm install'
            }
        }
    }
}