pipeline{
    agent{
        docker{
        
            args '-p 3030:3030'
        }
    }

    stages{
        stage('Build'){
            steps{
                sh 'npm install'
            }
        }
    }
}